services:
  - type: web
    name: discord-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: START_BOT
        value: "1"
      - key: DISCORD_TOKEN
        sync: false
